version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - FIREBASE_ADMIN_CREDENTIAL=/run/secrets/firebase_admin.json
    secrets:
      - firebase_admin.json
    restart: unless-stopped
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - backend
secrets:
  firebase_admin.json:
    file: ./firebase_admin.json 